displayName: Header transformation - Extended
type: middleware

import: github.com/m4rc3l-h3/htransformation

summary: 'Transform headers'

testData:
  Rules:
    - Rule:
      Name: 'Header renaming'
      Header: 'X-Traefik-*'
      Value: 'X-custom'
      Type: 'Rename'
    - Rule:
      Name: 'Header addition'
      Header: 'NewHeader'
      Value: 'True'
      Type: 'Set'
    - Rule:
      Name: 'Header deletion'
      Header: 'Cache-Control'
      Type: 'Del'
    - Rule:
      Name: 'Header joining'
      Header: 'Accept-Language'
      Sep: ', '
      Values:
        - 'Foo'
        - 'Bar'
      Type: 'Join'
