
services:
  traefik:
    image: traefik:v3.6.9
    ports:
      - "8080:80"       # Web
      - "8081:8080"     # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets/traefik_config:/etc/traefik
      - .:/plugins-local/src/github.com/m4rc3l-h3/headermodifications
    tty: true

  whoami:
    image: traefik/whoami # https://github.com/traefik/whoami
    command: -name whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.middlewares=example@file"
