http:
  middlewares:
    example:
      plugin:
        headermodifications:
          Rules:
            - Name: 'Set test header'
              Header: 'X-Test-Test'
              Value: 'Passed'
              Type: 'Set'
              HeaderPrefix: ^
            # - Type: AllowClients
            #   Name: 'AllowClients'
            #   LanValue: "LAN"
            #   WanValue: "WAN"
            #   TrustedHeader: "X-Forwarded-Origin"
            #   Debug: true
            #   AllowLan: false
            #   WanIPs: ["172.24.0.1"]
            #   RejectStatus: 403
